version: '3.6'

services:
  react-blog:
    image: nginx
    restart: always
    container_name: react-blog
    volumes:
      - ./build:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=react-blog.timoteojorge.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=react-blog.timoteojorge.com
      - LETSENCRYPT_EMAIL=timoteojorge@gmail.com
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy